(function(){
var f=true,g=null,h=false,aa=encodeURIComponent,i=window,ba=escape,j=navigator,m=undefined,ea=parseInt,n=document,p=Math;function fa(a,b){return a.toString=b}
var ga="appendChild",q="push",r="toString",s="valueOf",t="length",ha="plugins",u="prototype",ia="round",v="slice",w="replace",ja="document",x="split",ka="cookie",la="charAt",z="userAgent",A="screen",B="indexOf",ma="body",C="write",oa="domain",pa="call",qa="opera",ra="random",sa="createElement",D="getParameter",ta="referrer",E="substring",ua="apply",va="contentWindow",G="getTime",H="join",wa="toLowerCase",I,J=this,K=function(a,b,c){var d=a[x]("."),e=c||J;!(d[0]in e)&&e.execScript&&e.execScript("var "+
d[0]);for(var k;d[t]&&(k=d.shift());)if(!d[t]&&b!==m)e[k]=b;else e=e[k]?e[k]:(e[k]={})};p.floor(p[ra]()*2147483648)[r](36);
var xa=function(a,b){var c=a.yb;if(arguments[t]>2){var d=Array[u][v][pa](arguments,2);c&&d.unshift[ua](d,c);c=d}b=a.Ab||b;a=a.zb||a;var e,k=b||J;e=c?function(){var l=Array[u][v][pa](arguments);l.unshift[ua](l,c);return a[ua](k,l)}:function(){return a[ua](k,arguments)};e.yb=c;e.Ab=b;e.zb=a;return e},ya=Date.now||function(){return(new Date)[G]()},za=function(a,b){function c(){}c.prototype=b[u];a.bd=b[u];a.prototype=new c};function Aa(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c}function Ba(a,b){if(a=="true")return f;if(a=="false")return h;return b};var Ca="pagead2.googlesyndication.com",Da="googleads.g.doubleclick.net",Ea="pubads.g.doubleclick.net",Fa="partner.googleadservices.com",Ga=Ca,Ha=Da,Ia=Ea,Ja=Fa;function M(a){return typeof aa=="function"?aa(a):ba(a)}function Ka(a){if(a in La)return La[a];return La[a]=j[z][wa]()[B](a)!=-1}var La={};function Ma(){return Ka("msie")&&!i[qa]}
function Na(){if(j[ha]&&j.mimeTypes[t]){var a=j[ha]["Shockwave Flash"];if(a&&a.description)return a.description[w](/([a-zA-Z]|\s)+/,"")[w](/(\s)+r/,".")}else if(j[z]&&j[z][B]("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=g}return b[r]()}else if(Ma()){c=g;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.Mc="always"}catch(k){if(b==6)return b[r]()}try{c=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(l){}}if(c){b=c.GetVariable("$version")[x](" ")[1];return b[w](/,/g,".")}}return"0"};var Oa=function(a,b){return a[B](b)!=-1};ya();var Pa,Qa,Ta,Ua,Va,Wa,Xa,Ya,Za,$a,ab=function(){return J.navigator?J.navigator[z]:g},bb=function(){return J.navigator};Wa=Va=Ua=Ta=Qa=Pa=h;var cb;if(cb=ab()){var db=bb();Pa=cb[B]("Opera")==0;Qa=!Pa&&cb[B]("MSIE")!=-1;Ua=(Ta=!Pa&&cb[B]("WebKit")!=-1)&&cb[B]("Mobile")!=-1;Wa=(Va=!Pa&&!Ta&&db.product=="Gecko")&&db.vendor=="Camino"}var eb=Pa,fb=Qa,gb=Va,ob=Ta,pb,qb=bb();pb=qb&&qb.platform||"";Xa=Oa(pb,"Mac");Ya=Oa(pb,"Win");Za=Oa(pb,"Linux");$a=!!bb()&&Oa(bb().appVersion||"","X11");var rb="",sb;
if(eb&&J[qa]){var tb=J[qa].version;rb=typeof tb=="function"?tb():tb}else{if(gb)sb=/rv\:([^\);]+)(\)|;)/;else if(fb)sb=/MSIE\s+([^\);]+)(\)|;)/;else if(ob)sb=/WebKit\/(\S+)/;if(sb){var ub=sb.exec(ab());rb=ub?ub[1]:""}};var vb=["30143070","30143071","30143072","30143073","30143074","30143075"],xb=function(a){if(typeof a.google_a1_eid=="string")return a.google_a1_eid;var b=Aa("<<<ADSENSE_ONE_FRACTION>>>",0);a.google_a1_eid=wb(vb,b);return a.google_a1_eid},wb=function(a,b){var c=p[ra]();if(c<b){var d=p.floor(c/b*a[t]);return a[d]}return""};var yb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",
google_gl:"gl",google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},zb={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",
google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",
google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Ab={google_only_pyv_ads:"pyv"};n.URL&&(n.URL[B]("?google_debug")>0||n.URL[B]("&google_debug")>0);function Bb(a,b,c,d){this.Ga=a;this.Ea=b;this.W=c;this.ja=d;if(!this.W)this.W="/";if(this.ja==g)this.ja=n[oa]}fa(Bb[u],function(){return"[GA_GoogleCookieInfo: value="+this.Ga+", expires="+this.Ea+", path="+this.W+"]"});function Cb(){this.L=this.vc();this.ma=h;if(!this.L)this.ma=this.Kb()}I=Cb[u];I.Ba="__gads=";I.ia="GoogleAdServingTest=";I.setCookieInfo=function(a){this.C=a.Ca[0];if(this.C!=g){this.L=this.C.Ga;this.Jc()}};I.Na=function(a){var b=(new Date)[s](),c=new Date;c.setTime(b+a);return c};I.Xb=function(){var a=15552000000,b=this.Na(a),c="ID=12345:T="+a,d="/",e=n[oa];return new Bb(c,b[s](),d,e)};var Db="http://"+Ja+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo";I=Cb[u];
I.Pb=function(a){if(!(this.L||!this.ma)){var b="script",c=n[oa],d=Db+"&client="+M(a)+"&domain="+M(c);n[C]("<"+b+' src="'+d+'"></'+b+">")}};I.Kb=function(){n.cookie=this.ia+"Good";var a=this.gb(this.ia),b=a=="Good";if(b){var c=this.Na(-1);n.cookie=this.ia+"; expires="+c.toGMTString()}return b};I.vc=function(){var a=this.gb(this.Ba);return a};I.gb=function(a){var b=n[ka],c=b[B](a),d="";if(c!=-1){var e=c+a[t],k=b[B](";",e);if(k==-1)k=b[t];d=b[E](e,k)}return d};
I.Jc=function(){if(!(this.C==g))if(this.L){var a=new Date;a.setTime(1000*this.C.Ea);var b=this.C.ja,c=this.Ba+this.L+"; expires="+a.toGMTString()+"; path="+this.C.W+"; domain=."+b;n.cookie=c}};var Eb=n,N=j,O=i;function Fb(){var a=Eb[ka]?Eb[ka]:"",b=O.history[t],c,d,e=[N.appName,N.version,N.language?N.language:N.browserLanguage,N.platform,N[z],N.javaEnabled()?1:0][H]("");if(O[A])e+=O[A].width+"x"+O[A].height+O[A].colorDepth;else if(O.ad){d=java.Tc.Oc.Xc().Yc();e+=d[A].width+"x"+d[A].height}e+=a;e+=Eb[ta]?Eb[ta]:"";for(c=e[t];b>0;)e+=b--^c++;return Mb(e)}
function Mb(a){var b=1,c=0,d,e;if(!(a==m||a=="")){b=0;for(d=a[t]-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Nb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Eb[oa];if("www."==a[E](0,4))a=a[E](4,a[t])}return Mb(a[wa]())};var Ob=n,Pb=Ba("<<<IS_CANARY_BINARY>>>",h),Qb=Ba("<<<IS_CANARY_DATA>>>",h),Rb=Ba("<<<IS_DEBUG_IP>>>",h),P=i;var Sb=function(a){this.lb=(this.na=a&&a.GA_jstiming)&&this.na.load};Sb[u].z=function(a,b){this.lb.tick(a,b)};Sb[u].ib=function(a){var b={};b.e=a;this.na.report(this.lb,b)};var Tb=function(){};za(Tb,Sb);Tb[u].z=function(){};Tb[u].ib=function(){};var Ub=function(a,b,c,d){if(c<=4){var e=b+"_"+c;d?a.z(e,d+"_"+c):a.z(e)}};var Q=P&&p[ra]()<Aa("<<<GAM_CSI_REPORT_PROBABILITY>>>",0.0010)&&P.GA_jstiming&&P.GA_jstiming.load&&P.location.protocol=="http:"?new Sb(P):new Tb(P);Q.z("js_load");function R(a){return typeof a=="function"}function Vb(a,b){if(typeof a!="string"||a[t]==0)return g;else if(typeof b!="string"||b[t]==0)return g;return S().la(a,b)}K("GA_googleAddSlot",Vb,m);function _GA_googleInitializeAdEngine(a){if(!T()){var b=Wb(a);delete U;U=b;T().Wa()}}K("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine,m);
function Xb(){S().Mb=f;_GA_googleInitializeAdEngine(g);var a=T().h;a=="sync"||a=="sync_sra"?T().D():S().Qb()}K("GA_googleFetchAds",Xb,m);function Yb(){_GA_googleInitializeAdEngine("iframe");i._GA_googleCookieHelper.Pb(i.GS_googleGetIdsForAdSenseService())}K("GA_googleUseIframeRendering",Yb,m);function Zb(){var a=i.GA_googleEnv[D]("google_ad_impl");a==g&&i.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}K("GA_googleUseSyncSRARendering",Zb,m);
function $b(a){if(!(T()==g))if(!(T().h=="iframe")){if(T().K)if(T().fa){var b=S().G(a);if(b==g)return;else if(!b.V)return}else return;else if(T().N(a)!=g&&!T().l)return;T().s(a)}}K("GA_googleFillSlot",$b,m);function ac(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;if(!(T()==g))if(!(T().h!="iframe")){S().la(a,b);var e=new bc(c,d,h,f);S().rb(b,e);T().s(b)}}K("GA_googleFillSlotWithSize",ac,m);function cc(){var a=new V(yb);delete W;W=a;delete U;U=g}K("GA_googleResetAll",cc,m);i.google_noFetch=h;
function dc(){i.google_noFetch=f}K("GA_googleNoFetch",dc,m);function ec(){i.google_delayFetch=f}K("GA_googleDelayFetch",ec,m);function bc(a,b,c,d){this.B=a;this.A=b;this.Da=c;this.V=d}fa(bc[u],function(){return"[GA_GoogleAdSlotAttr: width="+this.B+", height="+this.A+", expandable="+this.Da+", enabled="+this.V+"]"});
function fc(a){for(var b=a||n.URL,c,d={},e=b[x]("?"),k=e[e[t]-1][x]("&"),l=0;l<k[t];l++){var o=k[l][x]("=");if(o[0])try{d[o[0][wa]()]=o[t]>1?i.Vc?decodeURIComponent(o[1][w](gc," ")):unescape(o[1]):""}catch(y){}}this.cb=c=d}fc[u].getParameter=function(a){return a==g?g:this.cb[a]};fc[u].setParameter=function(a,b){this.cb[a]=b};function hc(a){return a[w](/&/g,"&amp;")[w](/</g,"&lt;")[w](/>/g,"&gt;")[w](/\"/g,"&quot;")}function ic(){this.$=g;this.db=h;this.Uc=(new Date)[s]()}
ic[u].Fb=function(a){if(!(this.$!=g))if(!this.db)if(this.$=i.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes")){var b=this.$[ja],c=[];c[q]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');
c[q]("<p>Google Ad Capture Window</p>");for(var d in a)R(a[d])||c[q](this.Ic(d,a[d]));c[q]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");c[q]("<script>displayTime('blocked', pageStartTime);<\/script>");c[q]("<p>Total Page Load Time (ms): <label id='total'></label>");c[q]("</body>\n</html>");var e=c[H]("\n"),k=i.GA_googleEnv[D]("google_capture_norender")!=g;k?b[C](hc(e)):b[C](e);b.close()}else this.db=f};
ic[u].Ic=function(a,b){var c="<script>slotStartTime = (new Date()).valueOf();<\/script>",d="<p>Slot "+a+"</p>",e;e=b==g||b.m==g?"No ad":b.m;var k="<p>Slot Time (ms): <label id='"+a+"'></label>",l='<script>displayTime("'+a+'", slotStartTime);<\/script>';return c+d+"\n"+e+"\n"+k+l};function jc(a){this.f={};this.Y=a}I=jc[u];I.kc=function(a){return a in this.Y};I.ka=function(a,b,c){if(a){b||(b="");if(this.kc(a))if((c=typeof c=="undefined"||c)||!this.f[a])this.f[a]=b}};
I.qc=function(a){for(var b in a.f)R(a.f[b])||this.f[b]||(this.f[b]=a.f[b])};I.getAttribute=function(a){return this.f[a]};I.k=function(){var a=[];for(var b in this.f)if(!R(this.f[b]))if(!(b=="google_gl"&&this.f.google_country!=g)){var c=yb[b]||zb[b]||Ab[b]||g,d=this.f[b];c&&d&&a[q](c+"="+M(d))}return a[H]("&")};function kc(a,b){this.Q=a;this.w=b;this.za=0;this.yc=this.pa=this.wa=h;this.wc=this.xc=this.La=this.Rb=g}I=kc[u];I.jb=function(){this.pa=f;this.Rb=(new Date)[s]()};I.Dc=function(){this.La=(new Date)[s]()};
I.Fc=function(){this.yc=f;this.xc=(new Date)[s]()};I.Ec=function(){this.wc=(new Date)[s]()};fa(I,function(){return"[GA_GoogleAdSlot: pubid="+this.Q+", name="+this.w+", loaded="+this.wa+", tries="+this.za+"]"});function V(a){this.b={};this.g=[];this.H={};this.Y=a;this.ea=new jc(this.Y);this.S={};this.Mb=h;this.q=g}I=V[u];I.la=function(a,b){var c=new kc(a,b);return this.b[c.w]=c};
I.Ua=function(a){var b=[];for(var c in this.b)if(!R(this.b[c])){if(a){var d=this.G(c);if(d==g||!d.V)continue}var e=this.b[c];e.pa||b[q](e)}return b};I.fc=function(a){return this.Ua(a)[t]};I.ac=function(){var a=[];for(var b in this.b){var c=this.b[b];R(c)||c.pa&&c.La==g&&a[q](b)}return a};I.ec=function(){var a=0;for(var b in this.b)if(!R(this.b[b])){var c=this.G(b);c!=g&&c.V&&a++}return a};I.xa=function(){for(var a in this.b)if(!R(this.b[a])){var b=this.b[a];b.jb()}};
I.ab=function(a){var b=this.b[a];b.jb()};I.$a=function(a){var b=this.b[a];b.Dc()};I.nc=function(a){var b=this.b[a];b.Fc()};I.v=function(a){var b=this.b[a];b.Ec();Ub(Q,"ga_render",this.g[t],"ga_srt")};I.Ra=function(){var a=0;for(var b in this.b)R(this.b[b])||a++;return a};fa(I,function(){var a="[AdData:",b=[];for(var c in this.b)R(this.b[c])||b[q](this.b[c][r]());for(var d in this.H)R(this.H[d])||b[q]("["+d+","+this.H[d]+"]");a+=b[H]();a+="]";return a});I.t=function(a){return this.b[a]};
I.sb=function(a,b){if(!(a==g||a[t]==0)){if(b==g||b[t]==0)b="";var c=this.H[a];this.H[a]=c==g?b:c+","+b}};function lc(a,b){S().sb(a,b)}K("GA_googleAddAttr",lc,m);V[u].qb=function(a,b){this.ea.ka(a,b)};function mc(a,b){S().qb(a,b)}K("GA_googleAddAdSensePageAttr",mc,m);V[u].r=function(a,b,c){if(!(a==g||a[t]==0)){if(T()==g||T().h!="iframe"){var d=this.t(a);if(d==g)return}var e=this.S[a];if(e==g)this.S[a]=new jc(this.Y);this.S[a].ka(b,c)}};function nc(a,b,c){S().r(a,b,c)}
K("GA_googleAddAdSenseSlotAttr",nc,m);V[u].$b=function(a){return this.S[a]};V[u].Qb=function(){if(this.q!=g)T().D();else{var a=[];for(var b in this.b)R(this.b[b])||a[q](b);var c=i.GS_googleGetIdsForAdSenseService(),d=i.google_new_gam_domain_enabled==1,e,k="http://";k+=d?Ia:Ja;e=k+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes";var l=e+"&client="+ba(c)+"&page_slots="+ba(a[H]());n[C]("<script src = '"+l+"'><\/script>")}};V[u].setAdSlotAttributes=function(a){this.q=a;T().fa=f;T().D()};
function oc(a){S().setAdSlotAttributes(a)}K("GA_googleSetAdSlotAttributes",oc,m);V[u].rb=function(a,b){if(this.q==g)this.q={};this.q[a]=b;T().fa=f};V[u].G=function(a){return this.q!=g?this.q[a]:g};function pc(a,b){this.cd=a;this.Lb=b}function qc(a,b){this.Lc=pc;this.Kc(qc.nb,a);this.m=b}fa(qc[u],function(){return"[GA_HTMLAdSlotContent expandable="+this.Lb+", html="+this.m+"]"});qc.prototype=new pc(qc.nb,h);
function rc(a,b,c){if(!c||c<0||c>1)c=0;this.Ac=p[ra]()<c;this.ic=a;this.Aa=b+"/pagead/gen_204?id="+M(a);this.jc=[]}rc[u].n=function(a,b){if(a&&a.match(/^\w+$/)&&b)this.Aa+="&"+a+"="+M(b)};rc[u].Ha=function(){var a=S();for(var b in a.b){var c=a.b[b];if(!R(c)&&c.Q!=g){this.n("pub_id",c.Q);break}}this.n("nslots",a.Ra()[r]());this.n("pub_url",n.URL);this.n("pub_ref",n[ta])};rc[u].Za=function(){if(!this.Ac||!this.ic||!this.Aa)return h;var a=new Image;a.src=this.Aa;this.jc[q](a);return f};
function X(a){this.i=g;this.q={};this.u=this.d="";this.l=a;this.o=this.da=this.I=h;this.h="sync";this.U=yb;this.K=f;this.fa=h}I=X[u];I.Wa=function(){this.I=i.GA_googleEnv[D]("google_nofetch")!=g||i.google_noFetch;this.da=i.GA_googleEnv[D]("google_norender")!=g;if(this.o=i.GA_googleEnv[D]("google_capture")!=g||i.GA_googleEnv[D]("google_capture_norender")!=g)this.da=f;this.Bc(i);this.d=this.u;var a=xa(this.tc,this);this.hb(i,a)};
I.hb=function(a,b){if(a.attachEvent){a.attachEvent("onload",b);return f}if(a.addEventListener){a.addEventListener("load",b,h);return f}return h};I.sa=function(a){if(a.google_new_gam_domain_enabled==1)return"http://"+Ia;return"http://"+Ja};I.Pa=function(){this.o&&i.GA_googleAdCapture.Fb(this.i)};
I.mc=function(){if(this.h=="sync_sra"){var a=S(),b=a.Ra(),c=a.g[t];if(b!=c){this.ca=new rc("sra_mismatch",this.sa(i),Aa("<<<LOG_FILLSLOT_MISMATCH_PROBABILITY>>>",0.0010));this.ca.n("correlator",this.j);this.ca.n("fslots",c[r]());this.ca.Ha();this.ca.Za()}}};I.pc=function(){Q.z("ga_onload");Q.ib(this.h)};
I.lc=function(){var a=S().ac();if(a[t]>0){this.P=new rc("missing_cb",this.sa(i),Aa("<<<LOG_MISSING_CALLBACK_PROBABILITY>>>",0.0010));this.P.n("pending",a[H]());this.P.n("correlator",this.j);this.P.n("impl",this.h);this.P.Ha();this.P.Za()}};I.tc=function(){this.pc();this.Pa();this.mc();this.lc()};I.Bc=function(a){var b=i.GA_googleEnv[D]("google_ad_url");if(b==g||b[t]==0)this.u=this.sa(a)+"/gampad/ads?";else{if(b[la](b[t]-1)!="?")b+="?";this.u=b}};I.F=function(){};I.ua=function(){return S().Ua(this.K)};
I.Sa=function(){return S().fc(this.K)};I.N=function(a){return this.i!=g?this.i[a]:g};var sc=function(){var a=j[z],b=a[B]("MSIE ");return b==-1?0:parseFloat(a[E](b+5,a[B](";",b)))},gc=/\+/g;I=X[u];I.Va=function(a){a=a[wa]();if(a[E](0,3)!="ca-")a="ca-"+a;return a};I.c=function(a,b){b!=g&&this.a(a,M(b[r]()))};I.a=function(a,b){if(b!=g)this.d+=this.d[la](this.d[t]-1)!="?"?"&"+a+"="+b:a+"="+b};
I.Oa=function(a){for(var b=this.ua(),c=[],d=[],e=[],k=b[t],l=0;l<k;l++){var o=b[l];e[q](o.w);if(!(a!=g&&a!=o.w)){c[q](o.w);d[q](this.Va(o.Q))}}this.c("client",d[0]);if(this.l)e[t]>0&&this.c("page_slots",e[H]());else{this.c("slotname",c[H]());S().g[t]>0&&this.c("page_slots",S().g[H]())}};I.gc=function(a,b){if(b!=g){var c=a.lastIndexOf("?"),d=a[B]("google_preview=",c),e=a[B]("&",d);if(e==-1){e=a[t]-1;d-=1}return a[E](0,d)+a[E](e+1,a[t])}return a};
I.dc=function(a,b){var c;a:{try{c=a.top[ja].URL==b.URL;break a}catch(d){}c=h}if(c)return b.URL;return b[ta]};I.cc=function(a,b){if(this.Ta(a,b)!=b.URL)return b[oa];return""};I.Ta=function(a,b){var c=S().ea.getAttribute("google_page_url");if(c)return c;return this.dc(a,b)};
I.Vb=function(a,b,c){this.c("url",this.gc(this.Ta(i,n),i.GA_googleEnv[D]("google_preview")));this.c("ref",n[ta]);this.c("lmt",(Date.parse(n.lastModified)/1000)[r]());this.a("dt",a[G]());if(n[ma]){var d=n[ma].scrollHeight,e=n[ma].clientHeight;e&&d&&this.c("cc",p[ia](e*100/d)[r]())}var k=i.GA_googleEnv[D]("deb");k!=g&&this.c("deb",k);var l=i.GA_googleEnv[D]("haonly");l!=g&&this.c("haonly",l);if(j[z][B]("MSIE ")>0){var o=S().ea;o.ka("google_encoding",n.charset,h)}var y=S().b,F=S().S,L=S().$b(b);o=S().ea;
var ca="";if(c){var da,Gb=this.U,Hb=[],Ib=[],Jb=o.f;for(var na in Gb)if(!R(na)){var hb=Gb[na];if(hb){var Ra="";if(Jb[na]!=g)Ra=M(Jb[na]);var Sa=[],Kb=-1,ib=-1;for(var jb in y)if(!R(y[jb])){++Kb;if(F[jb]==g)Sa[q]("");else{var Lb=F[jb].f;if(Lb[na]!=g){Sa[q](M(M(Lb[na])));ib=Kb}else Sa[q]("")}}if(ib>=0){var Dc=M(Ra),kb=[];kb[q](Dc);for(var lb=0;lb<=ib;++lb)kb[q](Sa[lb]);Ib[q](hb+","+kb[H](","))}else Ra&&Hb[q](hb+"="+Ra)}}var mb=[];mb[q](Hb);mb[q](Ib);da=mb;var nb=[];da[0]&&da[0][t]>0&&nb[q](da[0][H]("&"));
da[1]&&da[1][t]>0&&nb[q]("sps="+da[1][H]("|"));ca=nb[H]("&")}else{if(L==g)L=o;else L.qc(o);ca=L.k()}if(ca)this.d+="&"+ca};I.Yb=function(a,b){var c=S().H,d=[];for(var e in c)R(c[e])||d[q](M(e)+"="+M(c[e]));this.c("cust_params",d[H]("&"));if(a._GA_googleCookieHelper){this.c("cookie",a._GA_googleCookieHelper.L);a._GA_googleCookieHelper.ma&&this.c("cookie_enabled","1")}a.google_new_gam_domain_checked==1&&a.google_new_gam_domain_enabled!=1&&this.a("dblk",1);var k=this.cc(a,b);k&&this.c("cdm",k)};
I.Wb=function(){var a=Eb[ka],b=p[ia]((new Date)[G]()/1000),c=O.google_analytics_domain_name,d=typeof c=="undefined"?Nb("auto"):Nb(c),e=a[B]("__utma="+d+".")>-1,k=a[B]("__utmb="+d)>-1,l=a[B]("__utmc="+d)>-1,o,y={},F=!!O&&!!O.gaGlobal;if(e){o=a[x]("__utma="+d+".")[1][x](";")[0][x](".");y.J=k&&l?o[3]+"":F&&O.gaGlobal.J?O.gaGlobal.J:b+"";y.ha=o[0]+"."+o[1];y.Ma=f}else{y.J=F&&O.gaGlobal.J?O.gaGlobal.J:b+"";y.ha=F&&O.gaGlobal.ha?O.gaGlobal.ha:(p[ia](p[ra]()*2147483647)^Fb()&2147483647)+"."+b;y.Ma=h}y.Wc=
d;y.va=F&&O.gaGlobal.va?O.gaGlobal.va:p[ia](p[ra]()*2147483647);O.gaGlobal=y;var L=i;this.a("ga_vid",L.gaGlobal.ha);this.a("ga_sid",L.gaGlobal.J);this.a("ga_hid",L.gaGlobal.va);this.a("ga_fc",L.gaGlobal.Ma);this.c("ga_wpids",L.Zc)};
I.hc=function(a,b){var c=a[A],d=j.javaEnabled(),e=-b.getTimezoneOffset();if(c){this.a("u_h",c.height);this.a("u_w",c.width);this.a("u_ah",c.availHeight);this.a("u_aw",c.availWidth);this.a("u_cd",c.colorDepth)}this.a("u_tz",e);this.a("u_his",i.history[t]);this.a("u_java",d[r]());j[ha]&&this.a("u_nplug",j[ha][t]);j.mimeTypes&&this.a("u_nmime",j.mimeTypes[t]);this.a("flash",Na())};
I.k=function(a){this.F();var b=new Date;this.Oa(a);this.Yb(i,n);i.GA_googleEnv[D]("google_preview")!=g&&this.a("gct",i.GA_googleEnv[D]("google_preview"));this.Wb();this.Vb(b,a,this.l);this.hc(i,b);this.d=this.d[E](0,2000);return this.d=this.d[w](/%\w?$/,"")};var tc="google_ads_iframe_"[t];X[u].aa=function(a){return"google_ads_iframe_"+a};X[u].O=function(a){var b=a.getAttribute("id"),c=b.substr(tc,b[t]-tc);return c};
X[u].M=function(a,b,c,d,e,k){var l=this.aa(a),o=[];if(k){var y=this.ta(a);o[q]("<div id=",y,">")}o[q]("<iframe id=",l," name=",l,' width="',d,'" height="',e,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",this.o?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" style="border:0px;"',' src="',hc(b),'"');c!=g&&o[q](' onload="',c,'"');o[q]("></iframe>");k&&o[q]("</div>");var F=o[H]("");n[C](F)};
X[u].createDOMIframe=function(a,b){var c=this.N(b),d=c.B,e=c.A,k=c.m,l=n[sa]("iframe");l.id=this.aa(b);l.name=this.aa(b);l.width=d;l.height=e;l.vspace=0;l.hspace=0;l.Sc="true";l.scrolling="no";l.marginWidth=0;l.marginHeight=0;l.frameBorder=0;l.style.border=0;var o=n.getElementById(a);o[ga](l);if(this.o){l[va][ja][C](hc(k));l.scrolling="auto"}else l[va][ja][C](k);l[va][ja].close();S().v(b)};function uc(a,b){T().createDOMIframe(a,b)}K("GA_googleCreateDomIframe",uc,m);
var vc=function(a){var b="http://"+Ga+"/pagead/inject_object_div.js";if(ea(sc(),10)>6)return h;if(a[B](b)<0)return h;return f};I=X[u];
I.vb=function(a,b){if(this.o)b=hc(b);var c,d=[],e=n.getElementsByTagName("base");if(e)for(var k=0,l=e[t];k<l;++k){var o=e[k],y=o.getAttribute("target");if(y){d[q]({xb:o,uc:y});o.removeAttribute("target")}}c=d;i.frames[a.name].contents=b;a.src=vc(b)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';if(c)for(var F=0,L=c[t];F<L;++F){var ca=c[F];ca.xb.setAttribute("target",ca.uc)}};
I.wb=function(a,b){var c=this.O(a),d=a[va]?a[va][ja]:a.contentDocument;if(d==g)if(n.implementation&&n.implementation.createDocument)d=n.implementation.createDocument("",c,g);else if(typeof ActiveXObject!="undefined")d=new ActiveXObject("Msxml.DOMDocument");else return;d.open("text/html","replace");this.o?d[C](hc(b)):d[C](b);d.close()};
I.Ya=function(a){var b=this.O(a),c=S().t(b);if(!c.wa){c.wa=f;var d=this.N(b),e=a.parentNode;if(d==g||d.m==g){e.removeChild(a);S().v(b)}else if(d.Da){e.innerHTML=d.m;S().v(b)}else{d.Qc?this.vb(a,d.m):this.wb(a,d.m);S().v(b)}}};I.ta=function(a){return"google_ads_div_"+a};I.Hb=function(a){var b=this.ta(a),c="<div id="+b+">",d=this.N(a);if(!(d==g)){c+=d.m;c+="\n</div>\n";n[C](c);S().v(a)}};I.Gb=function(a){var b=this.ta(a),c="<div id="+b+">";c+="\n</div>\n";n[C](c);return b};
I.Z=function(){if(!this.K)return f;if(this.Sa()>0)return f;else if(S().ec()==0)return h};I.setAdContentsBySlot=function(a){Ub(Q,"ga_srt",S().g[t],"_ga_start");if(this.i==g){this.i=a;for(var b in a)R(a[b])||S().$a(b)}else for(b in a)if(!R(a[b])){this.i[b]=a[b];S().$a(b)}var c=h;for(b in a)if(!R(a[b])){var d=a[b];if(c){d.Ca=[i._GA_googleCookieHelper.Xb()];c=h}d!=g&&d.Ca!=g&&i._GA_googleCookieHelper.setCookieInfo(d)}};function wc(a){T().setAdContentsBySlot(a)}K("GA_googleSetAdContentsBySlot",wc,m);
function Y(a){X[pa](this,a);this.K=h;this.j=(new Date)[G]();this.h=a?"sync_sra":"sync"}za(Y,X);Y[u].F=function(){this.d=this.u;this.c("correlator",this.j[r]());this.a("output","json_html");this.a("callback","GA_googleSetAdContentsBySlotForSync");this.l?this.a("impl","ss"):this.a("impl","s");var a=0,b=f;for(var c in this.i)if(!R(this.i[c])){var d=this.i[c];if(d.Fa==m){b=h;break}else a=2*a+(d.Fa?1:0)}b&&this.a("prev_afc",a);this.l||this.ub(S().g,this.i)};
Y[u].ub=function(a,b){if(a&&b){for(var c=[],d=[],e=a[t]-1,k=0;k<e;k++){var l=a[k],o=b[l];if(o&&o.pb&&o.ob){c[q](o.pb[0]);d[q](o.ob[0])}else{c[q]("");d[q]("")}}if(c[t]>0){var y=c[H](","),F=d[H](",");this.c("a2ids",F);this.c("cids",y)}}};Y[u].Ob=function(a){var b=S().b,c=b[a];if(!(c==g))if(!this.I){this.k(c.w);S().ab(a);n[C]("<script src = '"+this.d+"'><\/script>")}};
Y[u].setAdContentsBySlotForSync=function(a){this.setAdContentsBySlot(a);if(this.l)if(S().g[t]==1){var b=S().g[0];this.ya(b);return}for(var c in a)R(a[c])||this.ya(c)};function xc(a){T().setAdContentsBySlotForSync(a)}K("GA_googleSetAdContentsBySlotForSync",xc,m);I=Y[u];I.D=function(){this.Z()};I.Nb=function(){this.k(g);n[C]("<script src = '"+this.d+"'><\/script>");S().xa()};I.s=function(a){S().g[q](a);Ub(Q,"_ga_start",S().g[t]);if(this.l)S().g[t]==1?this.Nb():this.ya(a);else this.Ob(a)};
I.Tb=function(a,b){if(a.$c){var c="script";b[C]("<"+c+' src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></'+c+">")}};I.ya=function(a){this.Ub(i,n,a)};
I.Ub=function(a,b,c){var d=S().t(c);if(!(d==g)){var e=this.N(c);S().nc(c);if(e==g||e.Pc){this.Tb(a,b,c);S().v(c)}else if(this.da&&!this.o)S().v(c);else if(e.Rc&&!e.Fa&&!this.o)this.Hb(c);else if(j[z][B]("MSIE ")>0){var k="GA_googleSyncAdSlotLoaded(this);";this.M(c,"about:blank",k,e.B,e.A,f)}else{var l=this.Gb(c);b[C]("<script>GA_googleCreateDomIframe('"+l+"' ,'"+c+"');<\/script>")}}};I.syncAdSlotLoaded=function(a){var b=this.O(a);S().t(b);this.Ya(a)};function yc(a){T().syncAdSlotLoaded(a)}
K("GA_googleSyncAdSlotLoaded",yc,m);function Z(a){X[pa](this,a);this.j=(new Date)[G]();this.h="async"}za(Z,X);Z[u].F=function(){this.d=this.u;this.Cc();this.c("correlator",this.j[r]());this.a("output","json_html");this.a("callback","GA_googleSetAdContentsBySlot");this.a("impl","a")};Z[u].Cc=function(){this.Ja=500;var a=i.GA_googleEnv[D]("google_async_delay");if(a!=g)this.Ja=1000*a};Z[u].D=function(){if(this.Z())this.I||i.setTimeout("GA_googleReallyFetchAds();",this.Nc)};
Z[u].reallyFetchAds=function(){if(!(this.Sa()==0)){var a=n.getElementsByTagName("head")[0];if(this.l){var b=n[sa]("script");b.src=this.k(g);a[ga](b);S().xa()}else{var c=S().b;for(var d in c)if(!R(c[d])){b=n[sa]("script");b.src=this.k(d);a[ga](b);S().ab(d)}}}};function zc(){T().reallyFetchAds()}K("GA_googleReallyFetchAds",zc,m);Z[u].s=function(a){var b=S().t(a);if(!(b==g)){S().g[q](a);var c="GA_googleAsyncAdSlotLoaded(this);",d=S().G(a);this.M(a,"about:blank",c,d.B,d.A,f)}};
Z[u].asyncAdSlotLoaded=function(a){var b=this.O(a);S().t(b);!this.I&&!this.da&&this.mb(a)};function Ac(a){T().asyncAdSlotLoaded(a)}K("GA_googleAsyncAdSlotLoaded",Ac,m);Z[u].mb=function(a){var b=this.O(a),c=S().t(b);if(this.i==g||this.i[b]==g){if(!(c.za>30)){i.setTimeout(function(){T().mb(a)},this.Ja);c.za++}}else this.Ya(a)};Z[u].Pa=function(){};function Bc(a){X[pa](this,a);this.j=(new Date)[G]();this.h="fallback"}za(Bc,X);
Bc[u].F=function(){this.d=this.u;this.c("correlator",this.j[r]());this.a("output","html");this.a("impl","fb")};Bc[u].D=function(){this.Z()};Bc[u].ra=function(a){var b;if(this.l){this.k(g);b=this.d+"&currentslot="+M(a)}else b=this.k(a);return b};Bc[u].s=function(a){var b=S().G(a);if(!(b==g)){S().g[q](a);if(!this.I){var c=this.ra(a);this.M(a,c,g,b.B,b.A,f)}}};function Cc(a){X[pa](this,a);this.j=(new Date)[G]();this.fa=f;this.h="iframe"}za(Cc,X);
Cc[u].F=function(){this.d=this.u;this.c("correlator",this.j[r]());this.a("output","html");this.a("impl","ifr")};Cc[u].D=function(){this.Z()};Cc[u].ra=function(a){var b;if(this.l){this.k(g);b=this.d+"&currentslot="+M(a)}else b=this.k(a);return b};Cc[u].s=function(a){var b=S().G(a);if(!(b==g)){S().g[q](a);if(!this.I){var c=this.ra(a);this.M(a,c,g,b.B,b.A,f)}}};
var Ec=function(){if(Ma()){var a=sc();return a<=5}else if(Ka("firefox")){var b=j[z][B]("Firefox")+8,c=ea(j[z][la](b),10),d=j[z][v](b);return c<1}else if(Ka("safari")){b=j[z][B]("Safari")+7;d=j[z][v](b);var e=ea(d,10);return e<412}else if(i[qa]!=g){b=j[z][B]("Opera")+6;d=j[z][v](b);c=ea(d,10);return c<9}else if(!Ma()&&!Ka("safari")&&Ka("mozilla")){b=j[z][B]("Netscape")+9;d=j[z][v](b);c=ea(d,10);return c<7}else return f},Fc=function(){if(Ma()){var a=sc();return a>5}else if(Ka("firefox")){var b=j[z][B]("Firefox")+
8,c=ea(j[z][la](b),10);j[z][v](b);return c>1}return h},Gc=function(){if(Ec())return"fallback";else if(i.google_delayFetch&&Fc())return"async";return"sync"},Wb=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=i.GA_googleEnv[D]("google_ad_impl");if(b==g)b=Gc()}switch(b){case "async":return new Z(h);case "sync":return new Y(h);case "sync_sra":return new Y(f);case "fallback":return new Bc(h);case "iframe":return new Cc(h);default:return new Bc(h)}},W;
function S(){W||(W=new V(yb));return W}var U;function T(){U||(U=g);return U}if(typeof i.GA_googleEnv=="undefined")i.GA_googleEnv=new fc;if(typeof i.GA_googleAdCapture=="undefined")i.GA_googleAdCapture=new ic;if(i._GA_googleCookieHelper==g)i._GA_googleCookieHelper=new Cb;Q.z("js_parse","js_load");Q.z("jl");var $={};for(var Hc in yb)$[Hc]=yb[Hc];for(var Ic in zb)$[Ic]=zb[Ic];$.google_slot_start_latency="l8nc_start";$.google_slot_end_latency="l8nc_end";$.google_prev_formats="prev_fmts";$.google_prev_slotnames="prev_slotnames";$.google_iframe_id="iframe_id";delete $.google_ad_output;var Jc=function(){this.T=0;this.p={};this.oa=[];this.Xa=this.ba=""};I=Jc[u];I.Qa=function(){return(new Date)[G]()};I.bb=function(a,b){var c=this.Qa();if(!this.T)this.T=c;this.p[a]||(this.p[a]={});this.p[a][b]=c;this.Xa=a};
I.oc=function(){this.oa[q](this.Qa())};I.Bb=function(){var a=this.oa[t],b={};b.ga={};for(var c in this.p){b.ga[c]={};for(var d in this.p[c])b.ga[c][d]=this.p[c][d]-this.T}b.qa=[];for(var e=0;e<a;e++)b.qa[q](this.oa[e]-this.T);this.ba=this.Xa;return b};I.Cb=function(){if(!this.p[this.ba])return g;var a={};for(var b in this.p[this.ba])a[b]=this.p[this.ba][b]-this.T;return a};
var Kc=function(){X[pa](this,f);this.K=h;this.j=(new Date)[G]();this.h="a1";this.X=0;this.U=$;this.Ia=this.kb=0;this.R=new Jc;this.eb=[];this.fb=[]};za(Kc,X);var Lc="http://"+Ha+"/pagead/adsone?",Mc="http://"+Ha+"/pagead/blankMessage.html?v=2";Kc[u].Ib=function(a){if(!a)return g;var b=this.sc();this.R.bb(b,"start");var c=this.tb(a,b);this.Zb(b);this.s(b);if(!this.Gc()){var d=this.bc();this.Hc(d)}this.zc();this.R.bb(b,"end");return c};
function Nc(a){var b;if(!T()){var c=new V($);delete W;W=c;var d=new Kc;delete U;U=d;var e=T();e.Wa();e.hb(i,xa(e.Ka,e))}b=T();return b.Ib(a)}K("A1_googleCreateSlot",Nc,m);I=Kc[u];I.Gc=function(){var a=xb(i);return a=="30143075"};I.bc=function(){var a=xb(i);if(a=="30143071")return 0;else if(a=="30143072")return 100;else if(a=="30143073")return 300;else if(a=="30143074")return 500;return 200};I.Hc=function(a){if(!this.X)this.X=i.setTimeout(xa(this.Ka,this),a)};
I.Db=function(){i.clearTimeout(this.X);this.X=0};I.tb=function(a,b){return S().la(a,b)};I.sc=function(){this.kb++;return"slot"+this.kb};I.rc=function(){this.Ia++;return"google_ads_backfiller"+this.Ia};
I.F=function(){this.d=Lc;this.a("correlator",ba(this.j[r]()));this.a("output","backfill");this.a("callback","setAdSenseOneContentsBySlot");this.a("impl",this.h);this.R.oc();var a=this.R.Cb(),b=this.R.Bb();if(b){this.a("fetch",b.qa[b.qa[t]-1]);a&&this.a("last_l8nc",a.end);var c=S().b;for(var d in c)if(!R(c[d])){S().r(d,"google_slot_start_latency",b.ga[d].start);S().r(d,"google_slot_end_latency",b.ga[d].end)}}};
I.Oa=function(){var a=this.ua(),b=a[t];if(b>0){this.c("client",this.Va(a[0].Q));for(var c=[],d=0;d<b;d++)c[q](a[d].w);this.c("page_slots",c[H]())}var e=xb(i);e&&this.c("eid",e)};I.Eb=function(a){var b=n[sa]("iframe"),c=this.rc();b.id=c;b.name=c;b.width=1;b.height=1;b.style.position="absolute";b.style.left="-5000px";b.src=a;n[ma][ga](b);return b};I.Ka=function(){this.Db();var a=this.ua(),b=a[t];if(!(b<=0)){var c=this.k(g);this.Eb(c);S().xa();this.Jb()}};
I.Zb=function(a){var b=S();for(var c in this.U){var d=i[c];d&&b.r(a,c,d)}b.r(a,"google_prev_formats",this.eb[H](","));b.r(a,"google_prev_slotnames",this.fb[H](","));b.r(a,"google_iframe_id",this.aa(a));if(i.google_ad_slot)this.fb[q](i.google_ad_slot);else i.google_ad_format&&this.eb[q](i.google_ad_format)};I.zc=function(){for(var a in this.U)a=="google_correlator"||(i[a]=g)};I.s=function(a){if(a in S().b){var b=Mc;this.M(a,b,g,i.google_ad_width,i.google_ad_height,h)}};
I.Jb=function(){var a=new V(this.U);delete W;W=a};var Oc=function(a,b,c){var d=xa(b,J,a),e=i.onerror;i.onerror=d;try{c()}catch(k){var l=k[r](),o="";if(k.Sb)o=k.Sb;var y=-1;if(k.lineNumber)y=k.lineNumber;var F=d(l,o,y);if(!F)throw k;}i.onerror=e};K("google_protectAndRun",Oc,m);
var Qc=function(a,b,c,d){if(p[ra]()<0.01){var e=["http://",Ga,"/pagead/gen_204","?id=jserror","&cb=",Pb?1:0,"&cd=",Qb?1:0,"&context=",M(a),"&msg=",M(b),"&file=",M(c),"&line=",M(d[r]()),"&url=",M(Ob.URL[E](0,512)),"&ref=",M(Ob[ta][E](0,512))];e[q](Pc());var k=e[H]("");P.google_image_requests||(P.google_image_requests=[]);var l=new Image;l.src=k;P.google_image_requests[q](l)}return!Rb};K("google_handleError",Qc,m);
var Pc=function(){var a=["&client=",M(P.google_ad_client),"&format=",M(P.google_ad_format),"&slotname=",M(P.google_ad_slot),"&output=",M(P.google_ad_output),"&ad_type=",M(P.google_ad_type)];return a[H]("")};function Rc(){Nc(i.google_ad_client)}Oc("show_ads_sra.main",Qc,Rc);
})()
